project:
  type: book
  output-dir: docs  # 关键：指定输出到 docs 文件夹以适配 GitHub Pages
  render:
    - "*.qmd"
    - "slides/*.qmd"

execute:
  freeze: auto

book:
  title: "数据采集与预处理"
  subtitle: "从网页爬虫到数据清洗的实战指南"
  author: "Hauqing Liu"
  date: now
  
  chapters:
    - index.qmd
    - part: "第一部分：绪论"
      chapters:
        - 0101-what-is-data-collection.qmd
        - 0102-what-is-data-preprocessing.qmd
        - 0103-introduction.qmd
    - part: "第二部分：数据采集方法"
      chapters:
        - 0201-data-collection-method.qmd
        - 0202-observation.qmd
        - 0203-experimentation.qmd
        - 0204-modeling.qmd
        - 0205-references.qmd
    - part: "第三部分：数据预处理方法"
      chapters:
        - 0301-data-cleaning-pandas.qmd
        - 0302-feature-engineering.qmd
    - part: "第四部分：数据采集实战"
      chapters:
        - 0401-data-cleaning-pandas.qmd
        - 0402-feature-engineering.qmd
    - 010-references.qmd
format:
  html:
    theme: cosmo
    css: custom.css
    number-sections: true
    number-depth: 3
    toc: true          # 开启右侧页内目录 (Table of Contents)
    toc-depth: 3       # 目录深度
    toc-title: "本页内容" # 自定义目录标题
    fig-width: 7
    fig-asp: 0.618
    fig-align: center
    out-width: 100%
    warning: false
    message: false
    include-in-header:
        - ga.html
    include-after-body:
        - giscus.html
        - text: |
              <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
              <script async src="https://hypothes.is/embed.js"></script>
  # 核心：左侧导航栏配置
    sidebar:
      style: "docked"  # 固定在左侧 (docked) 
      search: true     # 开启搜索框
      collapse-level: 2 # 默认展开的层级
      
    # 页面布局优化
    grid:
      sidebar-width: 300px # 左侧栏宽度
      body-width: 900px    # 正文宽度
      margin-width: 300px  # 右侧目录栏宽度
      
    # 页脚 (可选)
    page-footer: 
      left: "Copyright 2026, Huaqing Liu"
      right: "Built with Quarto" 